# Generated by Django 5.0.3 on 2024-04-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScorerTable',
            new_name='Scorer_Table',
        ),
    ]
