# Generated by Django 5.0.3 on 2024-06-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
