# Generated by Django 5.0.3 on 2024-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_team_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
