# Generated by Django 5.0.3 on 2024-05-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_league_match_league_season_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.league'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
