# Generated by Django 5.0.3 on 2024-05-13 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.match')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.player')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.type_of_card')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.match_event')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.penalty')),
            ],
        ),
        migrations.AddField(
            model_name='match_event',
            name='penalty',
            field=models.ManyToManyField(through='base.MatchPenalty', to='base.penalty'),
        ),
    ]
