# Generated by Django 5.0.3 on 2024-05-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_type_of_card_match_event_penalty_matchpenalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchpenalty',
            name='match_event',
        ),
        migrations.RemoveField(
            model_name='matchpenalty',
            name='penalty',
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player')),
            ],
        ),
        migrations.CreateModel(
            name='Match_Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.match')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.penalty')),
            ],
        ),
        migrations.DeleteModel(
            name='Match_Event',
        ),
        migrations.DeleteModel(
            name='MatchPenalty',
        ),
    ]
