# Generated by Django 5.0.3 on 2024-05-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_matchpenalty_match_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_penalty',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.match'),
        ),
    ]
