# Generated by Django 5.0.3 on 2024-05-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_match_penalty_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.goal')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.match')),
            ],
        ),
    ]
