# Generated by Django 5.0.3 on 2024-05-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_match_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_goal',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='card',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='match',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='player',
        ),
        migrations.RemoveField(
            model_name='match_penalty',
            name='penalty',
        ),
        migrations.AddField(
            model_name='match_goal',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.player'),
        ),
        migrations.AddField(
            model_name='match_goal',
            name='time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match_penalty',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.type_of_card'),
        ),
        migrations.AddField(
            model_name='match_penalty',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.player'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
