# Generated by Django 5.0.3 on 2024-05-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_match_goal_player_alter_match_goal_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_goal',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.team'),
        ),
        migrations.AddField(
            model_name='match_penalty',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.team'),
        ),
        migrations.AddField(
            model_name='squad',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.match'),
        ),
        migrations.AlterField(
            model_name='match_goal',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.match'),
        ),
        migrations.AlterField(
            model_name='match_penalty',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.match'),
        ),
    ]
