# Generated by Django 5.0.3 on 2024-05-17 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_match_goal_team_match_penalty_team_squad_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='matchday_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.matchday'),
        ),
    ]
