# Generated by Django 5.0.3 on 2024-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_matchday_match_matchday_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
