# Generated by Django 5.0.3 on 2024-05-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_match_finished'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matchday',
            new_name='Queue',
        ),
        migrations.RemoveField(
            model_name='match',
            name='matchday_number',
        ),
        migrations.AddField(
            model_name='match',
            name='queue_number',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.queue'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='goals_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
