# Generated by Django 5.0.3 on 2024-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_matchday_queue_remove_match_matchday_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
