# Generated by Django 5.0.3 on 2024-05-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_player_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.league'),
        ),
        migrations.AlterField(
            model_name='match',
            name='queue_number',
            field=models.IntegerField(default=1),
        ),
    ]
