# Generated by Django 5.0.3 on 2024-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_player_goals_queue_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='queue_number',
            field=models.IntegerField(default=1),
        ),
    ]
